#!/usr/bin/env python3
"""Generate the integrated Manual-I roadmap after the M3 operator-freeze gate.

This generator writes governance and roadmap artifacts only. Scientific Cs
operator rows are generated by the dedicated M3 builder. It does not execute a
resonance search, attach a physical clock-state interpretation, activate an SI
anchor, read an observation target, or compute a residual or score.
"""
from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "manual" / "data" / "roadmap"
VERSION = "v40.03r05"


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


MILESTONES = [
    dict(milestone_id="M0", sequence="0", scope="protocol", title="Exact native/projection/observation protocol baseline", status="complete", target_release="v40.03r01", inputs="shared exactness appendix", outputs="unified kernel; execution modes; read-only trace; exact projection; observation packet; typed residual", exit_condition="shared protocol tests pass", manual2_effect="carried_forward"),
    dict(milestone_id="M1H", sequence="1", scope="manual1", title="Cs M1 canonical execution-ledger and detector-freeze hardening", status="complete", target_release="v40.03r03.2", inputs="Cs identity occurrence; shared topology family; frozen kernels", outputs="non-temporal kernel inventory; enumerate_all mass ledger; pre-detection freeze manifest; blind p:q classifier; capacity-fill audit", exit_condition="exact stage mass conservation; mutation rejection; p:q=1:2 under declared L=6; recurrence unclaimed", manual2_effect="deferred_frozen"),
    dict(milestone_id="M2", sequence="2", scope="manual1", title="Native coupled core-outer primitive recurrence certificate", status="complete", target_release="v40.03r04", inputs="M1H admitted occurrence; target-free core-outer coupling operator; connected recurrence trace", outputs="six-state connected primitive recurrence certificate; realized integer bip count; exact mass audit; counterfactual specificity audit", exit_condition="full-period closure; no proper-prefix closure; exact mass conservation; realized integer bip count; target frequency absent", manual2_effect="deferred_frozen"),
    dict(milestone_id="M3", sequence="3", scope="manual1", title="Cs-scoped native atom-field interaction operator freeze", status="complete", target_release="v40.03r05", inputs="M2 recurrence certificate; native coupled states; target-free phase-domain and interaction declarations", outputs="Q/Z drive domain; two-window finite-state operator; exact response contract; zero-perturbation policy; selector; controls; SI activation guard", exit_condition="operator frozen but unexecuted; phase aliases canonical; target frequency absent; SI anchor inactive", manual2_effect="deferred_frozen"),
    dict(milestone_id="M4", sequence="4", scope="manual1", title="Target-Blind Native Resonance Search", status="next", target_release="v40.03r06", inputs="M3 frozen operator; exact Q/Z phase grid; frozen controls", outputs="exact cadence response ledger; candidate/candidate-set/interval/unresolved state; control audit", exit_condition="all responses exact; no target frequency; selector output and alias classes materialized", manual2_effect="deferred_frozen"),
    dict(milestone_id="M5", sequence="5", scope="manual1", title="Native resonance and zero-perturbation certificate", status="planned", target_release="v40.03r07", inputs="M4 response ledger; M3 perturbation and selector contracts", outputs="native zero-perturbation resonance cadence; period if invertible; contrast; alias; stability; controls", exit_condition="exact unique/tied/interval/unresolved status; primitive and refinement audits; target absent", manual2_effect="deferred_frozen"),
    dict(milestone_id="M6", sequence="6", scope="manual1", title="Correspondence mode and exact SI anchor gate", status="planned", target_release="v40.03r08", inputs="M5 native resonance certificate; exact SI reference card; mode declaration", outputs="SI_realization_binding or independent_empirical_validation contract; anchor identity/supersession card", exit_condition="SI realization opens only for unique exact zero-perturbation resonance; independent validation requires separate time scale", manual2_effect="deferred_frozen"),
    dict(milestone_id="M7", sequence="7", scope="manual1", title="Exact SI causal-metric projection cards", status="planned", target_release="v40.03r09", inputs="M6 active anchor; exact SI defining-constant cards; physical-domain contracts", outputs="second; hertz; vacuum-null-path metre; photon/transition energy; frequency-derived mass-equivalent cards", exit_condition="authoritative rows integer/reduced-rational; domain and anchor-state hashes frozen", manual2_effect="deferred_frozen"),
    dict(milestone_id="M8", sequence="8", scope="manual1", title="Native cut calculus and circle-boundary refinement", status="planned", target_release="v40.03r10", inputs="M7 report cards; finite boundary/path/refinement declarations", outputs="boundary difference; finite accumulation; path certificate; native shell packet; circle report/refinement ledgers", exit_condition="native closure and report-space R_CA separately typed; symbolic pi enclosure/refinement audit", manual2_effect="deferred_frozen"),
    dict(milestone_id="M9", sequence="9", scope="manual1", title="Native tracer and run-tumble fractal-coordinate migration", status="planned", target_release="v40.03r11", inputs="M7 exact reports; M8 native operators; historical 3D fixture", outputs="native tracer packet; run/tumble event ledger; exact rational 3D projection; observation uncertainty packet; blind join gate", exit_condition="native packet target-independent; historical Brownian fixture retyped; information loss and support audited", manual2_effect="deferred_frozen"),
    dict(milestone_id="M10", sequence="10", scope="manual1", title="Hydrogen frequency-ratio holdout", status="planned", target_release="v40.03r12", inputs="M6 anchor; M7 frequency card; independently frozen hydrogen native and observation packets", outputs="dimensionless recurrence ratio and branch-isolated exact residual", exit_condition="candidate/map/observation/join hashes frozen before unseal; empirical result typed", manual2_effect="deferred_frozen"),
    dict(milestone_id="M11", sequence="11", scope="manual1", title="Tau temporal audit", status="planned", target_release="v40.03r13", inputs="M6 anchor; M7 time card; native Tau packet; rational observation interval", outputs="typed interval-aware temporal residual", exit_condition="duration semantics explicit; uncertainty-aware residual complete; empirical result typed", manual2_effect="deferred_frozen"),
    dict(milestone_id="M12", sequence="12", scope="manual1", title="Existing-prediction migration audit", status="planned", target_release="v40.03r14", inputs="M8-M11 and carried Manual-I lanes", outputs="release-wide typed migration audit", exit_condition="every carried result identifies native/projection/target-support/scope/empirical/rendering disposition", manual2_effect="deferred_frozen"),
    dict(milestone_id="M13", sequence="13", scope="cross_manual", title="Manual I consolidation and shared-protocol-v2 proposal", status="planned", target_release="v40.03r15", inputs="M1H-M12 completed protocol ledgers", outputs="consolidated Manual-I release; proposal-only shared protocol v2 artifacts; anchor supersession policy", exit_condition="protocol audit complete; empirical outcomes may match mismatch interval_overlap or abstain", manual2_effect="opens_reassessment"),
    dict(milestone_id="M14", sequence="14", scope="manual2", title="Manual II reassessment and native protein-fold calculus", status="planned", target_release="v40.03r16", inputs="M13 exit; frozen Manual-II source; synchronized shared protocol v2", outputs="reassessed Manual-II release; native fold/projection/observation separation", exit_condition="shared v2 synchronized; protein native packet distinct from metric/contact reports; target gates independently governed", manual2_effect="active_reassessment"),
]

DEPENDENCIES = [
    dict(gate_id="M1H", depends_on="M1_structural_occurrence_gate", required_state="complete", blocked_action="native coupled recurrence construction", reason="canonical exact-mass execution and cryptographic pre-detection admission must close before recurrence"),
    dict(gate_id="M2", depends_on="M1H", required_state="complete", blocked_action="atom-field operator freeze", reason="primitive recurrence must be derived from a connected target-free coupled-state trace"),
    dict(gate_id="M3", depends_on="M2", required_state="complete", blocked_action="target-blind native resonance search", reason="drive domain and interaction operator must bind to a certified recurrence"),
    dict(gate_id="M4", depends_on="M3", required_state="complete", blocked_action="native resonance certificate", reason="response search follows the frozen phase domain, windows, operator, controls, and selector"),
    dict(gate_id="M5", depends_on="M4", required_state="complete", blocked_action="correspondence mode and SI anchor", reason="native cadence, alias class, contrast, perturbation extraction, and stability must be certified"),
    dict(gate_id="M6", depends_on="M5", required_state="exact_unique_zero_perturbation_resonance_or_mode_remains_pending", blocked_action="exact SI-valued report rows", reason="SI realization requires a unique exact resonance; independent validation requires a separately frozen time scale"),
    dict(gate_id="M7", depends_on="M6", required_state="complete", blocked_action="native cut and circle report audit", reason="typed SI report cards require an active anchor and explicit physical-domain contracts"),
    dict(gate_id="M8", depends_on="M7", required_state="complete", blocked_action="native tracer/run-tumble migration", reason="circle and finite-cut migration require exact report-card and refinement infrastructure"),
    dict(gate_id="M9", depends_on="M7;M8", required_state="complete", blocked_action="observation-qualified tracer comparison", reason="native motion and exact projection lanes require the anchor and finite native operators"),
    dict(gate_id="M10", depends_on="M6;M7", required_state="complete", blocked_action="hydrogen holdout join", reason="holdout requires frozen anchor and frequency report contract"),
    dict(gate_id="M11", depends_on="M6;M7", required_state="complete", blocked_action="Tau time join", reason="Tau projection requires frozen anchor and time report contract"),
    dict(gate_id="M12", depends_on="M8;M9;M10;M11", required_state="complete", blocked_action="Manual-I consolidation", reason="migration audit requires native-operator, motion, and holdout lanes"),
    dict(gate_id="M13", depends_on="M12", required_state="protocol_audit_complete", blocked_action="Manual-II reassessment", reason="empirical mismatch does not block consolidation when ledgers are complete and valid"),
    dict(gate_id="M14", depends_on="M13", required_state="complete", blocked_action="Manual-II shared-v2 activation", reason="Manual-II reassessment follows synchronized proposal and artifact-baseline audit"),
]

CRITERIA = [
    dict(criterion_id="R1", category="protocol", criterion="Shared exactness appendix remains canonical through M12", status="active_M3_to_M12", required_evidence="shared protocol source hash unchanged", effect="main/shared/manual2 frozen"),
    dict(criterion_id="R2", category="M3", criterion="Atom-field operator is target-blind and unexecuted", status="complete", required_evidence="input lock; Q/Z domain; exact operator; perturbation policy; selector; controls; SI guard", effect="admits M4 search"),
    dict(criterion_id="R3", category="anchor", criterion="SI realization requires unique exact zero-perturbation resonance", status="planned_M5_M6", required_evidence="exact unique candidate; alias count one; contrast; controls; stability", effect="prevents premature anchor"),
    dict(criterion_id="R4", category="migration", criterion="Empirical mismatch is a typed result and does not block consolidation", status="active", required_evidence="protocol_audit_status separate from empirical_result", effect="scientific mismatches retained"),
    dict(criterion_id="R5", category="manual2", criterion="Manual II remains frozen until synchronized reassessment", status="deferred_M14", required_evidence="manual-2 source/PDF hash unchanged", effect="prevents unsynchronized shared changes"),
]

FILE_MATRIX = [
    dict(phase="M1H", path="MANUAL_I_ROADMAP.md", action="modify", role="integrated milestone sequence and governance", freeze_policy="manual1_open"),
    dict(phase="M1H", path="manual/appendices/E_native_si_anchor_iteration_plan.tex", action="modify", role="rendered integrated roadmap", freeze_policy="manual1_open"),
    dict(phase="M1H", path="manual/data/roadmap/", action="modify", role="machine-readable roadmap and dependencies", freeze_policy="manual1_open"),
    dict(phase="M2-M6", path="manual/appendices/F_cs133_structural_occurrence_gate.tex", action="modify", role="Cs occurrence recurrence atom-field search certificate correspondence and anchor sequence", freeze_policy="manual1_open"),
    dict(phase="M2-M6", path="manual/data/cs133/", action="add_or_modify", role="native recurrence atom-field operator search certificate and anchor ledgers", freeze_policy="manual1_open"),
    dict(phase="M2-M6", path="manual/scripts/build_cs133_*", action="add_or_modify", role="deterministic Cs gate generators", freeze_policy="manual1_open"),
    dict(phase="M2-M6", path="tests/test_manual1_cs133_*", action="add_or_modify", role="Cs gate freeze integrity and exact arithmetic tests", freeze_policy="manual1_open"),
    dict(phase="M7", path="manual/appendices/G_exact_si_causal_metric_projection_cards.tex", action="add", role="exact SI report-card contracts", freeze_policy="manual1_open"),
    dict(phase="M7", path="manual/data/exact_metric/", action="add", role="integer/rational SI and mass-equivalent report cards", freeze_policy="manual1_open"),
    dict(phase="M8", path="manual/appendices/H_native_fractal_coordinate_cut_calculus.tex;manual/appendices/I_circle_boundary_refinement_audit.tex", action="add", role="finite native operator and circle report protocols", freeze_policy="manual1_open"),
    dict(phase="M9", path="manual/appendices/J_native_tracer_run_tumble_migration.tex", action="add", role="native tracer and observation-lane migration", freeze_policy="manual1_open"),
    dict(phase="M13", path="manual/data/roadmap/shared_protocol_v2_proposal/", action="add", role="proposal-only synchronized shared protocol v2 artifacts", freeze_policy="manual1_open_shared_frozen"),
    dict(phase="M14", path="manual-2/sections/;manual-2/data/protein/", action="add_or_modify", role="native protein-fold calculus reassessment", freeze_policy="manual2_reassessment_only"),
]

PLAN_MD = '''# Manual I Integrated Native-Simulation Roadmap

## Current state

```text
M1H complete
M2 native recurrence complete: six realized bips
M3 target-blind atom-field operator freeze complete
M4 target-blind native resonance search next
SI anchor inactive
Manual II frozen pending M14
```

## Governing architecture

The canonical machine field remains `fractal_octave_coordinate`. Realized anchor-eligible duration uses `realized_integer_bip_count`; expected rational and octave-refined durations remain separately typed.

```text
native occurrence
-> exact D.E.C. execution
-> read-only trace
-> native recurrence
-> target-blind atom-field operator
-> native resonance search and certificate
-> correspondence mode
-> exact SI reports
-> independent observation packet
-> typed join and residual
```

## M3 operator contract

The current operator is an exact rational finite-state phase-coincidence model. It freezes a Q/Z drive domain, canonical half-open phase representatives, two recurrence-derived interaction windows, exact state-mass rules, an all-zero perturbation policy, exact response representation, a two-window alias-resolving selector, control audits, and a later SI-activation guard.

No physical clock-state label, target frequency, observation packet, resonance result, residual, or score enters M3.

## Cadence and period typing

The primary search output is a native cadence in turns per bip. A period is inverted only for a positive unique rational cadence. Tied candidate sets, rational intervals, zero cadence, or unresolved results keep the period and SI anchor pending.

## Correspondence modes

After a native zero-perturbation resonance is certified, M6 declares one of:

```text
SI_realization_binding
independent_empirical_validation
```

SI realization calibrates the native scale and is not an independent prediction of the defining caesium frequency. Independent validation requires a separately frozen bips-per-second scale.

## Downstream lanes

M7 materializes exact SI report cards under explicit physical-domain contracts, including a vacuum null-path card only where the path/frame policy is declared. Every report carries an anchor_supersession_policy. M8 and M9 implement finite native geometry and motion. The carried Brownian lane remains a historical exact 3D projected-coordinate audit, while M9 creates a target-independent native_tracer_motion_packet. Hydrogen and Tau are independent holdouts after the anchor/report contracts close. M12 produces the typed migration audit. M13 proposes shared protocol v2 while shared source remains frozen; M14 performs the synchronized Manual-II reassessment.
'''


def build_manifest(tracked: list[Path]) -> None:
    manifest = {
        "manifest_id": "manual1_si_anchor_iteration_plan",
        "version_scope": VERSION,
        "release_role": "cs_scoped_native_atom_field_interaction_operator_freeze",
        "main_note_status": "frozen",
        "manual_i_status": "M3_complete_open_for_M4_to_M12",
        "shared_protocol_status": "frozen_through_M12_shared_v2_proposal_at_M13",
        "manual_ii_status": "frozen_carried_forward_pending_M14_reassessment",
        "current_gate_state": {
            "M1H": "complete_v40.03r03.2",
            "M2_native_recurrence": "complete_v40.03r04",
            "M3_atom_field_operator": "complete_v40.03r05_frozen_not_executed",
            "next_scientific_gate": "M4_target_blind_native_resonance_search",
            "fractal_coordinate_serialized_field": "fractal_octave_coordinate",
            "duration_semantics_registry": "realized_integer_bip_count|expected_rational_duration|octave_refined_sub_bip_duration",
            "primitive_recurrence_bip_count": "6",
            "drive_phase_domain": "Q_mod_Z_with_canonical_half_open_representatives",
            "arithmetic_domain": "exact_rational_finite_state_operator",
            "native_resonance_search": "not_started",
            "native_resonance_certificate": "not_materialized",
            "physical_clock_state_interpretation": "pending_M6_correspondence_mode",
            "target_frequency_input": "absent",
            "bips_per_aod_second": "not_materialized",
            "SI_anchor": "inactive",
            "milestone_order_role": "release_planning_order",
            "dependency_graph_role": "authoritative_execution_order",
            "manual_ii_reassessment": "deferred_until_M14_v40.03r16",
            "candidate_universe_gate": "carried_forward_pending_manual2_lane",
        },
        "files": [
            {"path": p.relative_to(ROOT).as_posix(), "bytes": p.stat().st_size, "sha256": sha256_file(p)}
            for p in tracked
        ],
    }
    (DATA / "manual1_si_anchor_plan_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def main() -> int:
    DATA.mkdir(parents=True, exist_ok=True)
    write_csv(DATA / "manual1_si_anchor_milestone_plan.csv", list(MILESTONES[0]), MILESTONES)
    write_csv(DATA / "manual1_si_anchor_gate_dependencies.csv", list(DEPENDENCIES[0]), DEPENDENCIES)
    write_csv(DATA / "manual1_manual2_reassessment_criteria.csv", list(CRITERIA[0]), CRITERIA)
    write_csv(DATA / "manual1_integrated_file_change_matrix.csv", list(FILE_MATRIX[0]), FILE_MATRIX)
    (DATA / "manual1_integrated_native_simulation_change_plan.md").write_text(PLAN_MD, encoding="utf-8")

    tracked = [
        DATA / "manual1_si_anchor_milestone_plan.csv",
        DATA / "manual1_si_anchor_gate_dependencies.csv",
        DATA / "manual1_manual2_reassessment_criteria.csv",
        DATA / "manual1_integrated_native_simulation_change_plan.md",
        DATA / "manual1_integrated_file_change_matrix.csv",
        ROOT / "manual" / "appendices" / "E_native_si_anchor_iteration_plan.tex",
        ROOT / "manual" / "data" / "cs133" / "cs133_structural_occurrence_manifest.json",
        ROOT / "manual" / "data" / "cs133" / "cs133_native_recurrence_manifest.json",
        ROOT / "manual" / "data" / "cs133" / "cs133_atom_field_operator_manifest.json",
        ROOT / "manual" / "scripts" / "build_integrated_manual1_roadmap.py",
    ]
    build_manifest(tracked)
    print(DATA / "manual1_si_anchor_plan_manifest.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
